#ifndef _DEFINE_H_
#define _DEFINE_H_

#include "DLL_Imaging\h\ImgManager.h"

#include "Bmp.h"
#include "ImgListOrgani.h"

//

#define EM_DESTROY_QUERY_WND				WM_USER + 0x001
#define EM_SHOW_QUERY_WND					WM_USER + 0x002
#define EM_HIDE_QUERY_WND					WM_USER + 0x003
#define EM_RELOAD_QUERY_WND					WM_USER + 0x004

#define MSG_UPDATE_SEL						WM_USER + 0x005

#define EM_DESTROY_SOSPESIISTOLOGICI_WND	WM_USER + 0x006
#define EM_SHOW_SOSPESIISTOLOGICI_WND		WM_USER + 0x007
#define EM_HIDE_SOSPESIISTOLOGICI_WND		WM_USER + 0x008

#define EM_DESTROY_WAITREMOTETHREADDLG		WM_USER + 0x009
#define EM_DESTROY_WAITIMPORTIMAGEDLG		WM_USER + 0x010
#define EPM_THREAD_IMPORT_SETPOS			WM_USER + 0x011
#define EPM_THREAD_RIMAGE_SETPOS			WM_USER + 0x012
#define EPM_THREAD_RIMAGE_ON				WM_USER + 0x013
#define EPM_THREAD_RIMAGE_OFF				WM_USER + 0x014
#define EPM_THREAD_STARTMONITORAGGIO		WM_USER + 0x015
#define TIMER_CHECK_MONITORAGGIO			WM_USER + 0x016
#define WM_EXTEDITCMB_CHANGED				WM_USER + 0x017

#define WM_WAITINGDICOM_CLOSING				WM_USER + 0x018

#define EPM_THREAD_PDF_COUNT_PAGES_UPDATE	WM_USER + 0x019
#define WM_WAITINGDICOM_AFTERMOVEESAME		WM_USER + 0x021 //Gabriel BUG 7768 - Continuous capture problem
#define WM_ACQUISITIONWAITER_CLOSING		WM_USER + 0x022 
#define WM_WAITINGAUTOIMPORT_CLOSING		WM_USER + 0x023 
// #define EPM_THREAD_PDF_COUNT_PAGES_EMPTY	WM_USER + 0x020

//

#define EPM_CHECK_OBBLIGATORY_FIELD			WM_USER + 0x050
#define EPM_FOCUS_OBBLIGATORY_FIELD			WM_USER + 0x051
#define EPM_APP_STATECHANGED				WM_USER + 0x052
#define EPM_PATIENTCHANGED					WM_USER + 0x053
#define EPM_EXAMCHANGED						WM_USER + 0x054
#define EPM_EXAM_EDIT						WM_USER + 0x055
#define EPM_EXAM_UPDATE						WM_USER + 0x056
#define EPM_EXAM_UNDO						WM_USER + 0x057
#define EPM_ITEMDIRTY						WM_USER + 0x058
#define EPM_PROPERTYGRID_NOTIFY				WM_USER + 0x059
#define EPM_ANALYZE_GRID_RULES				WM_USER + 0x060
#define EPM_LOAD_GRID_RULES					WM_USER + 0x061
#define EPM_EDIT_GRID_ITEM_ENTER			WM_USER + 0x062
#define EPM_GRIDDIRTY						WM_USER + 0x063

//

#define AMBURN_NOTIFICATION					WM_USER + 0x100
#define AMBURN_USER_INTERACTION				WM_USER + 0x101
#define BACKUPDATI_PROGRESS					WM_USER + 0x102

#define EPM_RESIZE_FORM						WM_USER + 0x106
#define EPM_THREAD_IMPORT_IMAGE				WM_USER + 0x107
#define EPM_THREAD_SYNCRO					WM_USER + 0x108 // per EndoxSyncro.dll, deve corrispondere ovviamente! //
#define EPM_CHECKVALUE						WM_USER + 0x110
#define EPM_PRINTINGTHREADENDED				WM_USER + 0x111

#define WM_ITEM_CHECK_CHANGED				WM_USER + 0x126

//

#define MSG_FORM_ANNULLAPAZIENTE			WM_USER + 0x200
#define MSG_FORM_ANNULLAESAME				WM_USER + 0x201
#define MSG_FORM_RESET						WM_USER + 0x202
#define MSG_FORM_LOAD						WM_USER + 0x203
#define MSG_FORM_SAVE						WM_USER + 0x204
#define MSG_FORM_READONLY					WM_USER + 0x205
#define MSG_FORM_SEARCHNEW					WM_USER	+ 0x206
#define MSG_FORM_CLONE						WM_USER + 0x208

#define MSG_FREEEDIT_FOCUS_LOST				WM_USER + 0x211

#define MSG_EDIT_UPDATED					WM_USER + 0x212

//

#define MSG_ENTER_USER						WM_USER + 0x255
#define MSG_ENTER_DEVICE					WM_USER + 0x256

#define MSG_ENTER_OPERATORE					WM_USER + 0x257
#define MSG_ENTER_SERIALESONDA				WM_USER + 0x258

//

#define EPM_TWAIN_ACQUIRE_NOTIFICATION		WM_USER + 0x300 // deve essere uguale ad AmTwain ovviamente! //
#define EPM_IMAGESEL_NOTIFY					WM_USER + 0x301

#define EPM_THUMB_DBLCLICK					WM_USER + 0x302
#define EPM_THUMB_DELETE					WM_USER + 0x303
#define EPM_THUMB_RENAME					WM_USER + 0x304
#define EPM_THUMB_ACQUIRE					WM_USER + 0x305
#define EPM_THUMB_EXPORT					WM_USER + 0x306
#define EPM_THUMB_IMPORT_FROM_DISK			WM_USER + 0x307
#define EPM_THUMB_IMPORT_FROM_TWAIN			WM_USER + 0x308
#define EPM_THUMB_COPY_TO_CLIPBOARD			WM_USER + 0x309
#define EPM_THUMB_PRINT						WM_USER + 0x310
#define EPM_THUMB_PRINT_PREVIEW				WM_USER + 0x311
#define EPM_THUMB_GET_MENU					WM_USER + 0x312
#define EPM_THUMB_COMPARE					WM_USER + 0x313
#define EPM_THUMB_IMPORT_FROM_DICOM4D		WM_USER + 0x314

#define WM_SELIMG							WM_USER + 0x315
#define WM_UNSELIMG							WM_USER + 0x316

#define EPM_CHANGE_TXTEXTCONTROL_PAGE_VIEW	WM_USER + 0x316
#define EPM_NUM_IMAGES_SELETECTED_NOTIFY	WM_USER + 0x317

//

#define MSG_AFTER_ELABIMAGE					WM_USER + 0x400
#define MSG_AFTER_CHANGECOMMENT				WM_USER + 0x401
#define MSG_REFRESH_IMAGES					WM_USER + 0x402
#define MSG_REFRESH_ALBUM					WM_USER + 0x403 //Gabriel - BUG Refresh álbum

//

#define EPM_RCLICK							WM_USER + 0x500
#define WM_TOOLBAR_PRESS_BUTTON				WM_USER + 0x501
#define WM_TOOLBAR_UPDATE_COMMAND_UI		WM_USER + 0x502

//

#define WM_MY_HELP							WM_USER + 0x600

//

#define WM_PRESS_PEDAL_1					WM_USER + 0x701
#define WM_PRESS_PEDAL_2					WM_USER + 0x702
#define WM_PRESS_PEDAL_3					WM_USER + 0x703
#define WM_PRESS_PEDAL_4					WM_USER + 0x704

//

#define WM_CURCHANGE						WM_USER + 0x800
#define WM_SHOWDROPDOWN						WM_USER + 0x801

#define WM_MONITORAGGIOLISTEV				WM_USER + 0x802
#define WM_MONITORAGGIO_VITALSIGN_LISTEV	WM_USER + 0x803
#define WM_MISURAZIONI_VITALSIGN_LISTEV		WM_USER + 0x803

#define WM_SEDICHANGED						WM_USER + 0x804
#define WM_SALECHANGED						WM_USER + 0x805
#define WM_AGENDECHANGED					WM_USER + 0x806
#define WM_PROTOCOLLOCHANGED				WM_USER + 0x807
#define WM_GENOMICA_FILTROVARIANTE			WM_USER + 0x808

#define WM_REFERTO_END_EDIT					WM_USER + 0x809
//

#define NUM_FIELD_ANAM					 11
#define	NUM_LABEL_TESTO					100
#define	NUM_LABEL_TESTO_RTF				 20
#define NUM_LABEL_TESTO_CL				 20
#define NUM_LABEL_DATAORA				 20
#define NUM_LABEL_TASTO_STAMPA			 20
#define NUM_LABEL_TASTO_BROWSER			 20
#define NUM_LABEL_TASTO_EXEC			 20
#define NUM_LABEL_ETICHETTE				 40
#define NUM_LABEL_TASTO_CHIUSURAFASE	 20
#define NUM_LABEL_GRIDCL				 40

//

#define _TESI_IMAGING_LABEL_PRINTER_NAME	"Etichette"
#define _TEXT_CONTROL_FIELD_LIMIT			1048576
//#define _TEXT_CONTROL_FIELD_LIMIT			262144

//

enum
{
	CMB_PAZ_FAMILIARI,
	CMB_PAZ_PARENTELA,
	CMB_PAZ_PROFESSIO,
	CMB_PAZ_NAZIONALI,

	CMB_ANA_FUMO,
	CMB_ANA_SIGA,
	CMB_ANA_CAFF,
	CMB_ANA_ALCO,
	CMB_ANA_SUPE,
	CMB_ANA_FARM,
	CMB_ANA_ASSU,

	CMB_ANA_INDAGINE,
	CMB_ANA_ICHIRURG,
	CMB_ANA_IENDOSCO,
	CMB_ANA_MALATTIE,

	CMB_ESA_ESTENS,
	CMB_ESA_FARMAC,
	CMB_ESA_STUDIO,
	CMB_ESA_CONTRO,
	CMB_ESA_PREMED,
	CMB_ESA_ACCESS,
	CMB_ESA_VALUTA,

	CMB_ESA_COMPLICANZE,
	CMB_ESA_COMPLICANZEPROVV,
	CMB_ESA_COMPLICANZETERAP,
	CMB_ESA_COMPLICANZEESITO,
	CMB_ESA_GUARIG,
	CMB_ESA_QUADRO,
	CMB_ESA_TERAPIACONSIGLIATA,
	CMB_ESA_TERAPIACONSIGLIATADOSAGG,
	CMB_ESA_TERAPIACONSIGLIATADURATA,
	CMB_ESA_TERAPIAINATTO,
	CMB_ESA_TERAPIAINATTODOSAGG,
	CMB_ESA_TERAPIAINATTODURATA,
	CMB_ESA_OSPEDALE,

	CMB_ESA_LIBERO000,
	CMB_ESA_LIBERO001,
	CMB_ESA_LIBERO002,
	CMB_ESA_LIBERO003,
	CMB_ESA_LIBERO004,
	CMB_ESA_LIBERO005,
	CMB_ESA_LIBERO006,
	CMB_ESA_LIBERO007,
	CMB_ESA_LIBERO008,
	CMB_ESA_LIBERO009,
	CMB_ESA_LIBERO010,
	CMB_ESA_LIBERO011,
	CMB_ESA_LIBERO012,
	CMB_ESA_LIBERO013,
	CMB_ESA_LIBERO014,
	CMB_ESA_LIBERO015,
	CMB_ESA_LIBERO016,
	CMB_ESA_LIBERO017,
	CMB_ESA_LIBERO018,
	CMB_ESA_LIBERO019,
	CMB_ESA_LIBERO020,
	CMB_ESA_LIBERO021,
	CMB_ESA_LIBERO022,
	CMB_ESA_LIBERO023,
	CMB_ESA_LIBERO024,
	CMB_ESA_LIBERO025,
	CMB_ESA_LIBERO026,
	CMB_ESA_LIBERO027,
	CMB_ESA_LIBERO028,
	CMB_ESA_LIBERO029,
	CMB_ESA_LIBERO030,
	CMB_ESA_LIBERO031,
	CMB_ESA_LIBERO032,
	CMB_ESA_LIBERO033,
	CMB_ESA_LIBERO034,
	CMB_ESA_LIBERO035,
	CMB_ESA_LIBERO036,
	CMB_ESA_LIBERO037,
	CMB_ESA_LIBERO038,
	CMB_ESA_LIBERO039,
	CMB_ESA_LIBERO040,
	CMB_ESA_LIBERO041,
	CMB_ESA_LIBERO042,
	CMB_ESA_LIBERO043,
	CMB_ESA_LIBERO044,
	CMB_ESA_LIBERO045,
	CMB_ESA_LIBERO046,
	CMB_ESA_LIBERO047,
	CMB_ESA_LIBERO048,
	CMB_ESA_LIBERO049,
	CMB_ESA_LIBERO050,
	CMB_ESA_LIBERO051,
	CMB_ESA_LIBERO052,
	CMB_ESA_LIBERO053,
	CMB_ESA_LIBERO054,
	CMB_ESA_LIBERO055,
	CMB_ESA_LIBERO056,
	CMB_ESA_LIBERO057,
	CMB_ESA_LIBERO058,
	CMB_ESA_LIBERO059,
	CMB_ESA_LIBERO060,
	CMB_ESA_LIBERO061,
	CMB_ESA_LIBERO062,
	CMB_ESA_LIBERO063,
	CMB_ESA_LIBERO064,
	CMB_ESA_LIBERO065,
	CMB_ESA_LIBERO066,
	CMB_ESA_LIBERO067,
	CMB_ESA_LIBERO068,
	CMB_ESA_LIBERO069,
	CMB_ESA_LIBERO070,
	CMB_ESA_LIBERO071,
	CMB_ESA_LIBERO072,
	CMB_ESA_LIBERO073,
	CMB_ESA_LIBERO074,
	CMB_ESA_LIBERO075,
	CMB_ESA_LIBERO076,
	CMB_ESA_LIBERO077,
	CMB_ESA_LIBERO078,
	CMB_ESA_LIBERO079,
	CMB_ESA_LIBERO080,
	CMB_ESA_LIBERO081,
	CMB_ESA_LIBERO082,
	CMB_ESA_LIBERO083,
	CMB_ESA_LIBERO084,
	CMB_ESA_LIBERO085,
	CMB_ESA_LIBERO086,
	CMB_ESA_LIBERO087,
	CMB_ESA_LIBERO088,
	CMB_ESA_LIBERO089,
	CMB_ESA_LIBERO090,
	CMB_ESA_LIBERO091,
	CMB_ESA_LIBERO092,
	CMB_ESA_LIBERO093,
	CMB_ESA_LIBERO094,
	CMB_ESA_LIBERO095,
	CMB_ESA_LIBERO096,
	CMB_ESA_LIBERO097,
	CMB_ESA_LIBERO098,
	CMB_ESA_LIBERO099,

	CMB_ESA_MOTIVOCONSENSO,
	CMB_ESA_TIPODEGENZAINT,
	CMB_ESA_TIPODEGENZAEST,
	CMB_ESA_MOTIVOCANCEL, // Luiz - 01/04/2019 - P3 - Processa nova fase - Libera Laudo
	CMB_ESA_ESAMIPREGRESSI
};

#define	NUM_MAX_BMP	6

#define	MAX_WEEK	536870912 // corrisponde a 2^29 dove 29 = 32 - 3 bit (per la datazione)

#define NUM_ESAMI_MAX	10
#define NUM_ESAMI_MIN	5

#define NUM_MOSAIC_MAX	8
#define NUM_MOSAIC_MIN	4

#define QUATTRO_IMMAGINI	4
#define SEDICI_IMMAGINI		16

#define DUE_IMMAGINI		2 // Sandro Gallina - 18/05/2005 // inserito per CAlbumConfrontoDlg //
#define SEI_IMMAGINI		6 // Sandro Gallina - 18/05/2005 // inserito per CAlbumConfrontoDlg //

#define INTERNO		0
#define ESTERNO		1

#define STAMPA_IMMAGINI		0
#define STAMPA_REPORT		1

#define EXT_WIN		".WIN"
#define EXT_IMG		".IMG"
#define EXT_AVI		".AVI"
#define EXT_MPG		".MPG"

#define EXT_DIAPO	EXT_WIN
#define EXT_ENDOX	EXT_IMG
#define EXT_FILM	EXT_MPG

#define FORM_MINI	image_jpg
#define FORM_IMM	(imageformat)theApp.m_nArchivioImmaginiFormato

#define	ERROR_NOTHING		 0
#define	ERROR_CRASH_DISK	-1
#define	ERROR_FULL_DISK		-2
#define	ERROR_CRASH_DB		-3
#define	ERROR_CRASH_MEMORY	-4

#define	NOTHING_MODE				0
#define MODIFY_RECORD_PAZIENTI		1
#define MODIFY_RECORD_ESAMI			2
#define ADD_RECORD_ESAMI			4
#define ADD_RECORD_PAZIENTI			8
#define FILTER_RECORD_PAZIENTI		16
#define FILTER_RECORD_ESAMI			32

#define REPORT_NOTHING	0
#define REPORT_FIELD	1
#define REPORT_IMAGE	2
#define REPORT_LABEL	3
#define REPORT_TEXT		4
#define REPORT_PARAM	5
#define REPORT_BMP		6
#define REPORT_LINE     9
#define REPORT_ORGAN   10

#define _ENDOX_MUTEX "Endox Mutex"
#define _TESIIMAGING_PREFIX "TESI IMAGING -"

#define BOOL_ESTERNI FALSE
#define BOOL_INTERNI TRUE

#define BOOL_NOTMENU FALSE
#define BOOL_FROMMENU TRUE

#define MEDICI_CURANTI  123
#define MEDICI_INVIANTI 456

// Sandro 25/09/2013 // Pazienti cronici //
#define TIPOCAMPO_LIBERO	1
#define TIPOCAMPO_SCORE		2
#define TIPOCAMPO_FARMACO	3

// Sandro 27/02/2014 // Fase dei campi obbligatori //
#define CO_FASE_CHIUSURA_STAMPA 1
#define CO_FASE_CONVALIDA		2
#define CO_FASE_LIBERA_LAUDO  	3 //Gabriel - P3

//
#define LIMITE_SUPERIORE_DIST 200

#define EXPORT_TIMER 70
#define POSTACQUISIZIONE_TIMER 73
#define ATTIVA_TASTO_TIMER 0x321

#define DISC_CD  10
#define DISC_DVD 11

//Ingressi monitor BARCO
#define _HD_SDI1			0X08

// Sandro 26/08/2010 //
#define VAL_RICERCA -1234

//Simone
#define MENU_STAMPA_ETICHETTE 60000
#define MENU_TUTORIAL_FILES 61000
#define FASI_ESAME 62000

//
class CFileBmp;
typedef struct STRUCTESAME
{
	// vecchie //
	CFileBmp* pFileBmp[NUM_MOSAIC_MAX];
	CString strPaziente;
	long nDataEsame;
	int nDiapoPage;
	int nMaxDiapo;

	// nuove //
	CImgListOrgani ImgListOrgani;
	long lPaziente;
	long lEsame;
	BOOL bConfirmed;
	CString strDvdLabel;
	CList <tagPunti> listPunti;
} structEsame;

enum TrackerState { normal, selected, active };
enum SelectModeDlg{ none, move, size };

typedef struct _Variables_
{
	long lIDItem;
	CString sVariable;
	CString sValue;
} VARIABLES;

typedef struct
{
	long m_lID;
	CString m_sSede;
} tagSede;

enum ScannerConnectionType
{
	twain = 0,
	windowsMessages
};

enum StatoInvioCentraleRefertazione
{
	crNonInviare = 0,
	crDaInviare,
	crInviato
};

enum StatoInvioControlloQualita
{
	cqNonInviare = 0,
	cqDaInviare,
	cqInviato
};

enum StreamingStatus
{
	disabled = 0,
	enabled,
	connected
};

enum IntegrationSendStatus
{
	errored = -1,
	notSent,
	sent,
	filtered,
	inProgress
};

enum MonitoringPhase
{
	pre = 1,
	intra,
	post,
	recoveryRoom,
	discharge
};

//Gabriel BUG 6225 - Lista DO
enum FormatoEta
{
	AnnoMeseGiornoAbbreviato = 0,
	SoloAnno,
	AnnoMese
};

//Gabriel - TCP
enum StatoInvioAltraUnita
{
	auNonInviare = 0,
	auDaInviare,
	auInviato
};

#endif /* _DEFINE_H_ */