#ifndef _FIELDDLG_H_
	#define _FIELDDLG_H_

class CDrawTool;

enum
{
	paziente_progressivo,
	paziente_codicefiscale,
	paziente_codicefiscale_largo,
	paziente_codicesanitario, 
	paziente_cognome,
	paziente_nome,
	paziente_nominativo_cn,
	paziente_nominativo_nc,
	paziente_sesso,
	paziente_natoil,
	paziente_natoa,
	paziente_professione,
	paziente_via,
	paziente_citta,
	paziente_cap,
	paziente_provincia,
	paziente_recapito,
	paziente_telefono1,
	paziente_telefono2,
	paziente_fax,
	paziente_cellulare1,
	paziente_cellulare2,
	paziente_email,
	paziente_medicocurante,
	paziente_medicotelefono,
	paziente_medicoindirizzo,
	paziente_medicoemail,
	paziente_dasegnalare,
	paziente_codicecliente,
	paziente_cognome2,
	paziente_nominativopadre,
	paziente_nominativomadre,
	paziente_eta,
	paziente_eta_soloanni,
	paziente_indirizzoricetta,
	paziente_assiden,
	paziente_codalfa,

	anamnesi_fumo,
	anamnesi_sigarette,
	anamnesi_alcol,
	anamnesi_superalcolici,
	anamnesi_caffe,
	anamnesi_farmaci,
	anamnesi_assunzione,
	anamnesi_peso,
	anamnesi_altezza,
	anamnesi_bmi,
	anamnesi_bsa,

	preliminari_progressivo,
	preliminari_data,
	preliminari_data_eng,
	preliminari_ora,
	preliminari_tipoesame,
	preliminari_tipoesame_codice,
	preliminari_tipoesame_colore,
	preliminari_sedeesame,
	preliminari_salaesame,
	preliminari_progressivoannuale,
	preliminari_codiceprenotazione,
	preliminari_internoesterno,
	preliminari_inviante1,
	preliminari_inviante2,
	preliminari_inviante3,
	preliminari_inviante_codice,

	preliminari_medico1,
	preliminari_medico1_firma0,
	preliminari_medico1_firma1,
	preliminari_medico1_firma2,
	preliminari_medico1_firma3,
	preliminari_medico1_firma4,
	preliminari_medico1_firma5,
	preliminari_medico1_firma6,
	preliminari_medico1_firma7,
	preliminari_medico1_firma8,
	preliminari_medico1_firma9,
	preliminari_medico1_immaginefirma,

	preliminari_medico2,
	preliminari_medico2_firma0,
	preliminari_medico2_firma1,
	preliminari_medico2_firma2,
	preliminari_medico2_firma3,
	preliminari_medico2_firma4,
	preliminari_medico2_firma5,
	preliminari_medico2_firma6,
	preliminari_medico2_firma7,
	preliminari_medico2_firma8,
	preliminari_medico2_firma9,
	preliminari_medico2_immaginefirma,

	preliminari_infermiere1,
	preliminari_infermiere1_matricola,
	preliminari_infermiere2,
	preliminari_infermiere2_matricola,
	preliminari_anestesista,
	preliminari_camera,
	preliminari_indicazioni,
	preliminari_indicazioni_grande,
	preliminari_farmacotrial,
	preliminari_premedicazioni,

	esame_procdiag_fisso,
	esame_procdiag_grande,
	esame_proctera_fisso,
	esame_proctera_grande,
	esame_condottofino,

	esame_firma_smartcard_utente,
	esami_firma_smartcard_numero,
	esami_firma_smartcard_entecertificato,
	esame_firma_sostituzione_motivo,
	esame_firma_annullamento_idprecedente,
	esame_firma_annullamento_dataprecedente,
	esame_firma_annullamento_motivo,
	// esame_firma_versione_referto,

	altridati_valutazione,
	altridati_prossimocontrollo,
	altridati_complicanze,
	altridati_terapia,
	altridati_provvedimenti,
	altridati_esito,
	altridati_tipovisita,
	altridati_studio,
	altridati_quadro,
	altridati_guarigione,
	altridati_durata,
	altridati_difficolta,
	altridati_terapiaconsigliata,
	altridati_strumenti,
	altridati_accessori,
	altridati_note,
	altridati_biopsie,

	referto_referto_fisso,
	referto_referto_grande,

	libero_riferimento,
	libero_000,
	libero_001,
	libero_002,
	libero_003,
	libero_004,
	libero_005,
	libero_006,
	libero_007,
	libero_008,
	libero_009,
	libero_010,
	libero_011,
	libero_012,
	libero_013,
	libero_014,
	libero_015,
	libero_016,
	libero_017,
	libero_018,
	libero_019,
	libero_020,
	libero_021,
	libero_022,
	libero_023,
	libero_024,
	libero_025,
	libero_026,
	libero_027,
	libero_028,
	libero_029,
	libero_030,
	libero_031,
	libero_032,
	libero_033,
	libero_034,
	libero_035,
	libero_036,
	libero_037,
	libero_038,
	libero_039,
	libero_040,
	libero_041,
	libero_042,
	libero_043,
	libero_044,
	libero_045,
	libero_046,
	libero_047,
	libero_048,
	libero_049,
	libero_050,
	libero_051,
	libero_052,
	libero_053,
	libero_054,
	libero_055,
	libero_056,
	libero_057,
	libero_058,
	libero_059,
	libero_060,
	libero_061,
	libero_062,
	libero_063,
	libero_064,
	libero_065,
	libero_066,
	libero_067,
	libero_068,
	libero_069,
	libero_070,
	libero_071,
	libero_072,
	libero_073,
	libero_074,
	libero_075,
	libero_076,
	libero_077,
	libero_078,
	libero_079,
	libero_080,
	libero_081,
	libero_082,
	libero_083,
	libero_084,
	libero_085,
	libero_086,
	libero_087,
	libero_088,
	libero_089,
	libero_090,
	libero_091,
	libero_092,
	libero_093,
	libero_094,
	libero_095,
	libero_096,
	libero_097,
	libero_098,
	libero_099,
	libero_rtf_000_fisso,
	libero_rtf_000_grande,
	libero_rtf_001_fisso,
	libero_rtf_001_grande,
	libero_rtf_002_fisso,
	libero_rtf_002_grande,
	libero_rtf_003_fisso,
	libero_rtf_003_grande,
	libero_rtf_004_fisso,
	libero_rtf_004_grande,
	libero_rtf_005_fisso,
	libero_rtf_005_grande,
	libero_rtf_006_fisso,
	libero_rtf_006_grande,
	libero_rtf_007_fisso,
	libero_rtf_007_grande,
	libero_rtf_008_fisso,
	libero_rtf_008_grande,
	libero_rtf_009_fisso,
	libero_rtf_009_grande,
	libero_rtf_010_fisso,
	libero_rtf_010_grande,
	libero_rtf_011_fisso,
	libero_rtf_011_grande,
	libero_rtf_012_fisso,
	libero_rtf_012_grande,
	libero_rtf_013_fisso,
	libero_rtf_013_grande,
	libero_rtf_014_fisso,
	libero_rtf_014_grande,
	libero_rtf_015_fisso,
	libero_rtf_015_grande,
	libero_rtf_016_fisso,
	libero_rtf_016_grande,
	libero_rtf_017_fisso,
	libero_rtf_017_grande,
	libero_rtf_018_fisso,
	libero_rtf_018_grande,
	libero_rtf_019_fisso,
	libero_rtf_019_grande,
	libero_cl_000_fisso,
	libero_cl_000_grande,
	libero_cl_001_fisso,
	libero_cl_001_grande,
	libero_cl_002_fisso,
	libero_cl_002_grande,
	libero_cl_003_fisso,
	libero_cl_003_grande,
	libero_cl_004_fisso,
	libero_cl_004_grande,
	libero_cl_005_fisso,
	libero_cl_005_grande,
	libero_cl_006_fisso,
	libero_cl_006_grande,
	libero_cl_007_fisso,
	libero_cl_007_grande,
	libero_cl_008_fisso,
	libero_cl_008_grande,
	libero_cl_009_fisso,
	libero_cl_009_grande,
	libero_cl_010_fisso,
	libero_cl_010_grande,
	libero_cl_011_fisso,
	libero_cl_011_grande,
	libero_cl_012_fisso,
	libero_cl_012_grande,
	libero_cl_013_fisso,
	libero_cl_013_grande,
	libero_cl_014_fisso,
	libero_cl_014_grande,
	libero_cl_015_fisso,
	libero_cl_015_grande,
	libero_cl_016_fisso,
	libero_cl_016_grande,
	libero_cl_017_fisso,
	libero_cl_017_grande,
	libero_cl_018_fisso,
	libero_cl_018_grande,
	libero_cl_019_fisso,
	libero_cl_019_grande,
	libero_dataora_000,
	libero_dataora_001,
	libero_dataora_002,
	libero_dataora_003,
	libero_dataora_004,
	libero_dataora_005,
	libero_dataora_006,
	libero_dataora_007,
	libero_dataora_008,
	libero_dataora_009,
	libero_dataora_010,
	libero_dataora_011,
	libero_dataora_012,
	libero_dataora_013,
	libero_dataora_014,
	libero_dataora_015,
	libero_dataora_016,
	libero_dataora_017,
	libero_dataora_018,
	libero_dataora_019,
	libero_integrazioni,

	form_codificadiagnosi_fisso,
	form_codificadiagnosi_grande,
	form_codificaregionale_fisso,
	form_codificaregionale_grande,
	form_codificaregionale_desc_fisso,
	form_codificaregionale_desc_grande,
	form_diagnosi_fisso,
	form_diagnosi_grande,
	form_indaginipregresse,
	form_pregressiesamistrumentali,
	form_interventichirurgici,
	form_interventiendoscopici,
	form_istologia_fisso,
	form_istologia_fisso_plus,
	form_istologia_grande,
	form_istologia_grande_plus,
	form_familiarita,
	form_osservazioni_fisso,
	form_osservazioni_grande,
	form_malattieprecedenti,
	form_monitoraggio_orizzontale,
	form_monitoraggio_verticale,
	form_monitoraggio_verticale_new,
	form_monitoraggio_farmaci,
	form_monitoraggio_infermiere,
	form_monitoraggio_note,
	form_terapiainatto,
	form_codificaregionale_5righe,
	form_fluoroscopia,
	form_accessori,

	subanatomia_campioni,
	subanatomia_inviorichiesta,
	subanatomia_idcampione,
	subanatomia_tipo,
	subanatomia_intervento,
	subanatomia_nrcampione,
	subanatomia_notecampione,
	subanatomia_suggerimenti1_fisso,
	subanatomia_suggerimenti1_grande,
	subanatomia_suggerimenti2,
	subanatomia_spedireritirare,
	subanatomia_indirizzoalternativo,
	subanatomia_note,
	
	subistologia_riga,
	subistologia_tipo,
	subistologia_organo,
	subistologia_sede,
	subistologia_numero,
	subistologia_procedura,
	subistologia_diagnosi,

	form_allergie,
	form_pacemaker,
	form_portatorepacemaker,
	form_anticoagulanti,
	form_antiaggreganti,

	form_anatomiapatologicatasti,

	form_rao,
	form_consensoinformato,

	preliminari_inviante_i,
	preliminari_inviante_e,

	form_sedeprevista,
	form_sederaggiunta,

	screening_complicanzeimmediate,
	screening_complicanzetardive,
	screening_pulizia,
	screening_causenoncompletamento,
	screening_tolleranza,
	screening_conclusioniscreening,
	screening_conclusionicolon,
	screening_diagnosifinale,
	screening_altreanomalie,

	preliminari_premedposologia,

	esame_mst_complicanze1_fisso,
	esame_mst_complicanze1_grande,
	esame_mst_complicanze2_fisso,
	esame_mst_complicanze2_grande,
	esame_mst_complicanze3_fisso,
	esame_mst_complicanze3_grande,

	form_breathtest_hp_risultato,
	form_breathtest_hp_valore1,
	form_breathtest_hp_valore2,
	form_breathtest_hp_differenza,

	form_sospensione_si_no,
	form_sospensione_data,
	form_sospensione_motivo,

	form_procedure_icd9,
	form_diagnosi_icd9,

	form_newaccessori_fisso,
	form_newaccessori_grande,

	esame_codesame,
	esame_tempochiusura,
	esame_tempoconvalida,
	esame_codicericovero,
	esame_barcodericovero,
	esame_dataoralock,
	esame_dataorasuperlock,

	inps_medico_codicefiscale,
	inps_reperibilita_cognome,
	inps_reperibilita_via,
	inps_reperibilita_cap,
	inps_reperibilita_comune,
	inps_reperibilita_provincia,
	inps_datainizio,
	inps_datafine,
	inps_tipocertificato,
	inps_diagnosinote,
	inps_numeroprotocollo,

	esamestrumentale_orainizio,
	esamestrumentale_orafine,
	esamestrumentale_durata_oreminuti,
	esamestrumentale_durata_solominuti,

	pazientecronico_score_hb,
	pazientecronico_score_s,

	studio_descrizione,
	studio_data,
	studio_tempotrascorso,

	utente_inserimentoesame,

	bostonscore_score_dx,
	bostonscore_score_mid,
	bostonscore_score_sx,
	bostonscore_score_totale,
	bostonscore_descrizione_totale,
	esame_temporetrazione,

	worklist_note,
	worklist_assiden,
	worklist_cognome,
	worklist_cognome2,
	worklist_nome,
	worklist_datanascita,
	worklist_comunenascita,
	worklist_indirizzoresidenza,
	worklist_comuneresidenza,
	worklist_capresidenza,
	worklist_telefono1,
	worklist_telefono2,
	worklist_cellulare1,
	worklist_cellulare2,
	worklist_codicefiscale,
	worklist_codicesanitario,
	worklist_codicestp,
	worklist_codiceteam,
	worklist_sesso,
	worklist_medicocurante,
	worklist_cittadinanza,
	worklist_provincia,

	utenteconvalida_anagrafica,
	utenteconvalida_firma0,
	utenteconvalida_firma1,
	utenteconvalida_firma2,
	utenteconvalida_firma3,
	utenteconvalida_firma4,
	utenteconvalida_firma5,
	utenteconvalida_firma6,
	utenteconvalida_firma7,
	utenteconvalida_firma8,
	utenteconvalida_firma9,
	utenteconvalida_immaginefirma,

	utentechiusura_anagrafica,
	utentechiusura_firma0,
	utentechiusura_firma1,
	utentechiusura_firma2,
	utentechiusura_firma3,
	utentechiusura_firma4,
	utentechiusura_firma5,
	utentechiusura_firma6,
	utentechiusura_firma7,
	utentechiusura_firma8,
	utentechiusura_firma9,
	utentechiusura_immaginefirma,	

	esame_urgente,

	esame_gridcl000,
	esame_gridcl001,
	esame_gridcl002,
	esame_gridcl003,
	esame_gridcl004,
	esame_gridcl005,
	esame_gridcl006,
	esame_gridcl007,
	esame_gridcl008,
	esame_gridcl009,
	esame_gridcl010,
	esame_gridcl011,
	esame_gridcl012,
	esame_gridcl013,
	esame_gridcl014,
	esame_gridcl015,
	esame_gridcl016,
	esame_gridcl017,
	esame_gridcl018,
	esame_gridcl019,
	esame_gridcl020,
	esame_gridcl021,
	esame_gridcl022,
	esame_gridcl023,
	esame_gridcl024,
	esame_gridcl025,
	esame_gridcl026,
	esame_gridcl027,
	esame_gridcl028,
	esame_gridcl029,
	esame_gridcl030,
	esame_gridcl031,
	esame_gridcl032,
	esame_gridcl033,
	esame_gridcl034,
	esame_gridcl035,
	esame_gridcl036,
	esame_gridcl037,
	esame_gridcl038,
	esame_gridcl039,

	utenteloggato,
	fleury_ficha,

	//Luiz - 13/05/2019 - P3 - Atualiza nome/sobrenome Médico - Inclui Médicos solicitantes
	medico_inviante2,
	medico_inviante3,
	medico_inviante4,

	paziente_identificazionepassaporto,	//Julio - BUG 3285 - Adequação de laudos
	paziente_identificazionedoc1,		//Julio - BUG 3285 - Adequação de laudos
	paziente_identificazionedoc2,		//Julio - BUG 3285 - Adequação de laudos
	
	referto_integrato_macro, //Julio - BUG 3744 - Retorno do Pathox para o TesiCapture
	referto_integrato_diag,  //Julio - BUG 3744 - Retorno do Pathox para o TesiCapture
	referto_integrato_firma, //Julio - BUG 3744 - Retorno do Pathox para o TesiCapture

	endox_report_field_num_total			// sempre ultimo questo //
};

struct endox_report_field
{
	long lID;

	CString sCombo;
	CString sReport;

	BOOL bEndox;
	BOOL bImageNT;
};

class CFieldDlg : public CDialog
{

public:

	CFieldDlg(CWnd* pParent, CRect rectPage, CDrawTool* pObj, CSize szPage);

	enum { IDD = IDD_REPORT_FIELD };

	CButton		m_ctrlFontButton;
	CButton		m_ctrlCheck;
	CEdit		m_ctrlTesto;
	CComboBox	m_ctrlCombo;
	CStatic		m_ctrlTipo;
	long		m_nLeft;
	long		m_nTop;
	long		m_nWidth;
	long		m_nHeight;
	CEdit		m_ctrlParam[2];

	static endox_report_field m_strFieldEndox[endox_report_field_num_total];

	CString		m_strTesto;
	BOOL		m_bCheck;
	int			m_nParam;
	int			m_nAlignment;
	int			m_nRotation;
	CDrawTool*  m_pObj;
	CRect		m_rectPage;
	CSize       m_szPage;

protected:

	virtual void DoDataExchange(CDataExchange* pDX);
	virtual BOOL OnInitDialog();
	virtual void OnOK();

	afx_msg void OnButton();

	DECLARE_MESSAGE_MAP()

private: 

	CButtonLocalize m_ctrlButtonCancel;
	CButtonLocalize m_ctrlButtonOK;

	CButtonLocalize m_ctrlRadioOriz;
	CButtonLocalize m_ctrlRadio90O;
	CButtonLocalize m_ctrlRadio90A;

	CStaticLocalize m_ctrlStaticDim;
	CStaticLocalize m_ctrlStaticPos;
	CStaticLocalize m_ctrlStaticX;
	CStaticLocalize m_ctrlStaticY;
	CStaticLocalize m_ctrlStaticWidth;
	CStaticLocalize m_ctrlStaticHeight;

};

#endif /* _FIELDDLG_H_ */