// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "Endox.h"
#include "RGLOCX.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CRGLOCX

IMPLEMENT_DYNCREATE(CRGLOCX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CRGLOCX properties

/////////////////////////////////////////////////////////////////////////////
// CRGLOCX operations
