// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "Endox.h"
#include "WSpellctrl.h"

/////////////////////////////////////////////////////////////////////////////
// CWspellctrl

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

IMPLEMENT_DYNCREATE(CWspellctrl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CWspellctrl properties

/////////////////////////////////////////////////////////////////////////////
// CWspellctrl operations
